@baseUrl = http://localhost:8080

### 배차
PATCH {{baseUrl}}/api/deliveries/1/assign
Content-Type: application/json

### 배달 시작
PATCH {{baseUrl}}/api/deliveries/1/start
Content-Type: application/json

### 배달 완료
PATCH {{baseUrl}}/api/deliveries/1/complete
Content-Type: application/json

### 배달 조회
GET {{baseUrl}}/api/deliveries/1
Content-Type: application/json

### 주문 기준 배달 조회
GET {{baseUrl}}/api/deliveries/order/1
Content-Type: application/json
