@baseUrl = http://localhost:8080

### 주문 생성
POST {{baseUrl}}/api/orders/new
Content-Type: application/json

{
  "storeId": 1,
  "address": "Daegu",
  "orderProducts": [
    {
      "productId": 1,
      "quantity": 2
    }
  ]
}

### 주문 승인
POST {{baseUrl}}/api/orders/accept/1
Content-Type: application/json

### 주문 거절
POST {{baseUrl}}/api/orders/reject/1
Content-Type: application/json

### 주문 취소
POST {{baseUrl}}/api/orders/cancel/1
Content-Type: application/json

### 내 주문 내역 조회
GET {{baseUrl}}/api/orders/my-orders
Content-Type: application/json
