@baseUrl = http://localhost:8080

### 라이더 회원가입
POST {{baseUrl}}/api/riders/new
Content-Type: application/json

{
  "name": "rider",
  "phone": "01012345678"
}

### 라이더 로그인
POST {{baseUrl}}/api/riders/login
Content-Type: application/json

{
  "phone": "01012345678"
}

### 라이더 상태 변경
PATCH {{baseUrl}}/api/riders/status
Content-Type: application/json

{
  "status": "AVAILABLE"
}

### 배차 대기 라이더 조회
GET {{baseUrl}}/api/riders/available
Content-Type: application/json
