@baseUrl = http://localhost:8080

### 고객 회원가입
POST {{baseUrl}}/api/users/signup
Content-Type: application/json

{
  "name": "kim",
  "username": "customer01",
  "password": "password1234",
  "address": "Daegu"
}

### 사장 회원가입
POST {{baseUrl}}/api/users/owners/signup
Content-Type: application/json

{
  "name": "lee",
  "username": "owner01",
  "password": "password1234",
  "address": "Daegu"
}

### 사장 로그인
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "username": "owner01",
  "password": "password1234"
}

### 고객 로그인
POST {{baseUrl}}/api/users/login
Content-Type: application/json

{
  "username": "customer01",
  "password": "password1234"
}

### 주소 변경
PATCH {{baseUrl}}/api/users/address
Content-Type: application/json

{
  "address": "Seoul"
}

### 비밀번호 변경
PATCH {{baseUrl}}/api/users/password
Content-Type: application/json

{
  "password": "newpassword1234"
}
